### ISSUE TITLE
Qubit type

### ISSUE THREAD

**Issue by marek-miller** [marek-miller/qst#28]
Many function take argument  like `target_qubit` that should be an integer type for which it is safe to assume:

```
target_qubit >=0 && target_qubit < qureg.num_qubits_represented()
```

A Qubit type should be a mutable reference to a particular site in `Qureg`.
As such, it is derived from `Qureg` and lives as long as a particular instance of `Qureg`.  
(Qureg cannot change the number of qubits they consist of, so one-time initial validation should suffice.)

Proceed as follows:
- [x] #44
- [x] #52 (technically not necessary, but convenient)
- [x] #40
- [x] Implement Send for Qureg
- [ ] Define the type, and minimal working implementation #37 
- [ ] Move some  one-qubit functions (like measure()) on-type:
     -  Change the function signature
     -  Remove index checks no longer needed
     -  Document the change
- [ ] Expand Qureg with methods returning iterators over qubit range (wait for #41)
- [ ] Write new / modify existing tests (integration test for `Qubit` and `Qureg` interfaces)
- [ ] #38

With such a type ready, some functions should be moved qubit module.

- [ ] one-qubit gates
  - [x] `hadamard()`
  - [x] controlled_not()
  - [ ] `pauli_x,y,z()`
  - [ ] etc.

**Comment by marek-miller** [comment]
`Qubit` can take `qureg` by shared ref. Allow multiple `qubit`s access the same `qureg`.  See example:

https://github.com/marek-miller/quest-bind/blob/47e0773cbd9481c57a732f2fe626583eb797189a/examples/locc.rs

**Comment by marek-miller** [comment]
#77 is probably a better way to solve this.  Close for now
